dbt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'', include('dbtapp.urls', namespace="dbtapp")),
    url(r'^admin/', include(admin.site.urls)),
)

dbtapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from dbtapp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^video/list/$', views.videoList, name='videoList'),
    #url(r'^video/new/$', views.videoNew, name='videoNew'),
    #url(r'^video/(?P<pk>\d+)/$', views.videoUpdate, name='videoUpdate'),
    url(r'^video/(?:(?P<pk>\d+)/)?$', views.videoUpdate, name='videoUpdate'),
    url(r'^video/(?P<pk>\d+)/type/(?P<imgtype>[1-3]{1})/$', views.videoStep, name='videoStep'),
    url(r'^video/(?P<pk>\d+)/edit/$', views.videoEdit, name='videoEdit'),
    url(r'^video/(?P<videoId>\d+)/type/(?P<imgtype>[1-3]{1})/remove/photo/(?P<photoId>\d+)/$', views.photoRemove, name='photoRemove'),
    url(r'^video/(?P<videoId>\d+)/remove/photo/(?P<photoId>\d+)/$', views.photoRemoveEdit, name='photoRemoveEdit'),
    url(r'^video/(?P<videoId>\d+)/photo/(?P<photoId>\d+)/add/desciption/$', views.photoDescriptionPost, name='photoDescriptionPost'),
    url(r'^video/remove/(?P<pk>\d+)/$', views.videoRemove, name='videoRemove'),
    url(r'^phantomjs/(?P<pk>\d+)/$', views.phantomjspk, name='phantomjspk'),
    url(r'^video/(?P<pk>\d+)/logoPost$', views.logoPost, name='logoPost'),
    url(r'^video/(?P<pk>\d+)/render', views.videoRender, name='videoRender'),
    #url(r'^riktigIndex/$', views.riktigIndex, name='riktigIndex')

    url(r'^drive/$', views.googleDrive, name='googleDrive'),
    url(r'^drive/callback$', views.googleDriveCallback, name='googleDriveCallback'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dbtapp/models.py
from django.db import models
from django.forms import Field
from django.utils.translation import ugettext_lazy
from celery.worker.strategy import default

Field.default_error_messages = {
    'required': ugettext_lazy("Hoppsan, detta fylldes inte i!")}

class Logo(models.Model):
    photoFile = models.ImageField()

class Video(models.Model):
    company_name = models.CharField(max_length=100, default = None)
    video_name = models.CharField(max_length=100, default = None)
    video_url = models.CharField(max_length=500, null=True, blank=True, default = None)
    logo = models.ForeignKey(Logo, null=True, blank=True, default = None)
    
class Photo(models.Model):
    video = models.ForeignKey(Video, null=True, blank=True, default = None)
    photoFile = models.ImageField()
    order = models.IntegerField()
    photoType = models.IntegerField(null=True, blank=True, default = None) 
    description = models.CharField(max_length=100, null=True, blank=True, default=None)
    # """
    # Description: Model Description
    # """
    # pass
   
# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=Photo)
def photo_delete(sender, instance, **kwargs):
    # Pass false so ImageField doesn't save the model.
    instance.photoFile.delete(False)

@receiver(pre_delete, sender=Logo)
def logo_delete(sender, instance, **kwargs):
    # Pass false so ImageField doesn't save the model.
    instance.photoFile.delete(False)

dbtapp/forms.py
from django import forms
from .models import Photo, Video, Logo
from django.forms.models import modelformset_factory

class PhotoForm(forms.ModelForm):
    """Image upload form."""
    oldPos = forms.IntegerField(required=False)
    newPos = forms.IntegerField(required=False)
    imgId = forms.IntegerField(required=False)
    class Meta:
    	model = Photo
    	fields = ('photoFile','description')
    	widgets = {
            'photoFile': forms.FileInput(
                attrs={'id': 'input', 'multiple': 'true', 'onchange': 'this.form.submit();'}
            ),
        }

class VideoForm(forms.ModelForm):
    """Video Create form."""
    class Meta:
    	model = Video
    	fields = ('company_name','video_name')

class PosForm(forms.ModelForm):
    oldPos = forms.IntegerField()
    newPos = forms.IntegerField()

class LogoForm(forms.ModelForm):
    class Meta:
        model = Logo
        fields = ('photoFile',)
        widgets = {
            'photoFile': forms.FileInput(attrs={'id': 'input-logo','onchange': 'postLogoForm(this);'}),
        }

class SettingsPhotoForm(forms.ModelForm):
    animation = forms.ChoiceField(choices=[(1, "Fade")] + [(2, "Slide")] + [(3, "Zoom")])
    class Meta:
        model = Photo
        fields = ('description',)
        widgets = {
            'description': forms.TextInput(
                attrs={'id': 'post-description-text', 'required': False, 'placeholder': 'Skriv in din beskrivning...'}
            ),
        }

dbtapp/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django import forms
from django.forms.formsets import formset_factory
import json
from subprocess import Popen, PIPE, STDOUT


from .models import Photo, Video
from .forms import *
from django.core.files.base import File
from django.conf.urls import url


def index(request):
    return render(request, 'dbtapp/Riktigindex.html')

def googleDrive(request):
    return render(request, 'dbtapp/googleDrive.html')

def googleDriveCallback(request):
    return render(request, 'dbtapp/googleDrive.html')

def videoList(request):
    video_list = Video.objects.order_by('-pk')
    return render(
        request,
        'dbtapp/videoList.html',
        {'video_list': video_list},
    )

def videoUpdate(request, pk=-1):
    #import pdb; pdb.set_trace()
    try:
        instance = Video.objects.get(pk=pk)
    except:
        instance = None
    form = VideoForm(request.POST or None, instance=instance)
    if form.is_valid():
        model = form.save()
        return redirect('dbtapp:videoStep', pk=model.pk, imgtype=1)
    else:
        if pk is not None:
            return render(
                request,
                'dbtapp/videoNew.html',
                {'form': form, 'videoKey': pk},)
        return render(
            request,
            'dbtapp/videoNew.html',
            {'form': form,'videoKey': None},
        )

def videoRemove(request, pk):
    video = Video.objects.get(pk=pk)
    photos = Photo.objects.filter(video = video)
    for photo in photos:
        if photo is not None:
            photo.delete()
    if video.logo is not None:
        video.logo.delete()
    video.delete()
    return redirect('dbtapp:videoList')

def photoRemove(request, videoId, imgtype, photoId):
    video = Video.objects.get(pk=videoId)
    if video is not None:
        photos = getSortedPhotos(video)
        found = False
        for i in range(0,len(photos)):
            p = photos[i]
            if p.pk == int(photoId):
                p.delete()
                found = True
            elif found:
                p.order = i-1
                p.save()
    return redirect('dbtapp:videoStep', pk = videoId, imgtype = imgtype)

def photoRemoveEdit(request, videoId, photoId):
    video = Video.objects.get(pk=videoId)
    if video is not None:
        photos = getSortedPhotos(video)
        found = False
        for i in range(0,len(photos)):
            p = photos[i]
            if p.pk == int(photoId):
                p.delete()
                found = True
            elif found:
                p.order = i-1
                p.save()
    return redirect('dbtapp:videoEdit', pk = videoId)


def getSortedPhotos(video):
    photos = Photo.objects.filter(video = video)
    orderedPhotos = [None] * len(photos)
    for photo in photos:
        orderedPhotos[photo.order] = photo
    return orderedPhotos

def generateSettings(photos):
    settingsForms = [None] * len(photos)
    for i in range(0,len(photos)):
        settingsForms[i] = SettingsPhotoForm(instance=photos[i])
    return settingsForms

def videoStep(request, pk, imgtype):
    video = Video.objects.get(pk=pk)
    photos = getSortedPhotos(video=video)
    #import pdb; pdb.set_trace()
    if request.method == 'POST':
        if 'photoFile' in request.FILES:
            count = len(photos) 
            for afile in request.FILES.getlist('photoFile'):
                photo = Photo(video=video, photoFile=afile, order=count, photoType=imgtype)
                photos.append(photo)
                photo.save()
                count = count + 1
    settingsForms = generateSettings(photos)
    return render (
        request,
        'dbtapp/step'+imgtype+'.html',
        {'settings': settingsForms, 'video': video, 'form': PhotoForm(), 'imgtype': imgtype},
    )

def videoEdit(request, pk):
    video = Video.objects.get(pk=pk)
    photos = getSortedPhotos(video=video)
    if request.method == 'POST':
        #form = PhotoForm(request.POST, request.FILES)
        #import pdb; pdb.set_trace()
        count = len(photos)    
        if 'photoFile' in request.FILES:
            print(request.FILES)
            for afile in request.FILES.getlist('photoFile'):
                photo = Photo(video=video, photoFile=afile, order=count)
                photos.append(photo)
                photo.save()
                count = count + 1
            return render(
                request,
                'dbtapp/preview.html',
                {'images': generateSettings(photos), 'video': video, 'form': PhotoForm(), 'logoForm': LogoForm(), 'logo': video.logo},
            )
        else:
            if request.is_ajax():
                #import pdb; pdb.set_trace()
                #import os; print(os.path.join(os.path.dirname( __file__ ))
                #print("AJAX!!!")
                #print("Old position: " + request.POST['oldPos'] + " New position: " + request.POST['newPos'] + " pk: " + request.POST['imgId'])
                oldPos = int(request.POST['oldPos'])
                newPos = int(request.POST['newPos'])
                key = request.POST['imgId']
                #import pdb; pdb.set_trace()
                if ((oldPos is not None) and (newPos is not None)):

                    photos[oldPos].order = newPos
                    photos[oldPos].save()

                    if oldPos < newPos:
                        #import pdb; pdb.set_trace()
                        minVal = oldPos
                        maxVal = newPos
                        xr = xrange(minVal+1,maxVal+1)
                        for i in xr:
                            photos[i].order = i - 1
                            photos[i].save()
                    else:
                        #import pdb; pdb.set_trace()
                        minVal = newPos
                        maxVal = oldPos
                        xr = xrange(minVal,maxVal)
                        for i in xr:
                            photos[i].order = i + 1
                            photos[i].save()
                    return HttpResponse('')
    else:
        form = PhotoForm()
        logoForm = LogoForm()
        # Render list page with the documents and the form
        return render(
            request,
            'dbtapp/preview.html',
            {'settings': generateSettings(photos), 'video': video, 'form': form, 'logoForm': logoForm, 'logo': video.logo},
        )

def logoPost(request, pk):
    if request.method == 'POST':
        form = LogoForm(request.POST, request.FILES)
        if form.is_valid():
            model = form.save()

            video = Video.objects.get(pk=pk)
            video.logo = model
            video.save() 

            response_data = {}
            response_data['result'] = 'Create post successful!'
            response_data['logo_pk'] = model.pk
            response_data['video_pk'] = video.pk
            response_data['video_name'] = video.video_name

            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

def photoDescriptionPost(request, videoId, photoId):
    if request.method == 'POST':
        instance = Photo.objects.get(pk=photoId)
        form = SettingsPhotoForm(request.POST, instance=instance)
        if form.is_valid():
            model = form.save()

            response_data = {}
            response_data['result'] = 'Create post successful!'
            response_data['photo_pk'] = model.pk
            response_data['description'] = model.description

            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )




def videoRender(request, pk):
    video = Video.objects.get(pk=pk)
    photos = getSortedPhotos(video=video)
    #import pdb; pdb.set_trace()
    
    return render (
        request,
        'dbtapp/videoRender.html',
        {'settings': generateSettings(photos), 'video': video},
    )
    

# import threading
# import time
# from celery import Celery
# from tasks import add
# from multiprocessing import Process, Queue
from dbtapp.tasks import renderVideo

def phantomjspk(request, pk):

    path = reverse('dbtapp:videoRender', kwargs={'pk': pk})
    
    url = request.build_absolute_uri(path)

    url_video = request.build_absolute_uri()
    url_list = url_video.split("/")
    url_video = "http://"+url_list[2]+"/"
    video = Video.objects.get(pk=pk)
    renderVideo.delay(url,url_video, pk, video.video_name)  # @UndefinedVariable

    # queue = Queue()
    # p = Process(target=renderVideo, args=(request, pk))
    # p.start()
    # p.join() # this blocks until the process terminates
    # result = queue.get()
    # print result
    # app = Celery('tasks', broker='amqp://guest@localhost//')
    # _thread = threading.Thread(target=renderVideo(request,pk))
    # import pdb; pdb.set_trace()
    # _thread.setDaemon(True)
    # _thread.start()
    return redirect('dbtapp:videoList')

# #@app.task
# def renderVideo(request,pk):
#     video = Video.objects.get(pk=pk)
#     phantomjsCommand = 'phantomjs'
#     phantomjsScript = 'dbtapp/phantomjsRenderVideo.js'
    
#     ffmpegCommand = "ffmpeg -y -c:v png -f image2pipe -r 25 -i - -c:v libx264 -pix_fmt yuv420p -movflags +faststart media/videos/"+str(video.pk)+"-"+video.video_name+".mp4"
#     print(ffmpegCommand)

dbtapp/templates/dbtapp/preview.html
{% extends "dbtapp/stepBase.html" %}
{% load staticfiles %}

{% block headerNumber %}
<div style="background-color: #FF9900" class="round-button-circle-Large round-button-Large"> <h1>5</h1> </div>
{% endblock %}

{% block headerText %}
Din film är snart klar! 
<span class="glyphicon glyphicon-question-sign sign" aria-hidden="true"></span>
{% endblock %}

{% block content %}	
<div class="row top-buffer-4">
	<div class="col-xs-5 col-sm-5 col-md-5 col-md-offset-2">	

	<div id="slideshow-container">

		<!--Gammalt kryss i högra hörnet. vad ks avi göra med det?-->
		<!--<a id="closeButton" href="#" title="Close"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>-->
		{% include 'dbtapp/_videoPartial.html' %}
	</div>
	<div id="controls">
		<div id="sliderWrapper">
			<div id="slider"></div>
			<button id="pause" type="button" class="btn btn-primary controll-button"><span class="glyphicon glyphicon-play"></span></button>
			<button id="repeat" type="button" class="btn btn-primary  controll-button"><span class="glyphicon glyphicon-repeat"></span></button>
		</div>
	</div>
</div>

<!--<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 text-left">
		<div id="logo-box">
			<img id="logo-img" src="{{ logo.photoFile.url }}">
			<p><b>Ladda upp logga:</b></p>
			<form id="logo-form" action="{% url 'dbtapp:logoPost' video.pk %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<p>{{ logoForm.photoFile }}</p>
			</form>
		</div>-->
<div class="col-xs-5 col-sm-5 col-md-5">		
		<!-- Bildserie -->
		<h3>Profil</h3>
		
		<h5 class="top-buffer-1">Ladda upp logga:</h5>
		<img id="logo-img" src="{{ logo.photoFile.url }}" alt="">
		<form id="logo-form" action="{% url 'dbtapp:logoPost' video.pk %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p>{{ logoForm.photoFile }}</p>
		</form>
		
		<div class="col-xs-3 col-sm-3 col-md-3 buffer-0">
			<h5>Text:</h5>
			<div class="color-box text-color"></div>
		</div>
		<div class="col-xs-9 col-sm-9 col-md-9 buffer-0">
			<h5>Bakgrund:</h5>
			<div class="color-box background-color"></div>
		</div>
				
		<div class="col-xs-5 col-sm-5 col-md-5 buffer">
			<h5>Font:</h5>
			<select id="font">
				<option id="font-size-1" value="'Roboto Condensed', sans-serif">Roboto Condensed</option>
				<option id="font-size-2" value="'Rochester', cursive">Rochester</option>
				<option id="font-size-3" value="'Shadows Into Light', cursive">Shadows Into Light</option>
				<option id="font-size-4" value="'Indie Flower', cursive">Indie Flower</option>
				<option id="font-size-5" value="'Pacifico', cursive">Pacifico</option>
				<option id="font-size-6" value="'Amatic SC', cursive">Amatic SC</option>
			</select>
		</div>
</div>

<!--TEST-->

<div class="spacing"></div>
		<div class="row">
			<div class="col-md-12">
				<ul id="images" class="list-group">
					{% if settings %}
					{% for form in settings %}
					<li rel="{{ form.instance.pk }}" class="col-xs-1 list-type-{{form.instance.photoType}}">
						<form class="post-settings-form" action="{% url 'dbtapp:photoDescriptionPost' video.pk form.instance.pk%}" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{% load widget_tweaks %}
							<div class="image-wrapper">
								<img class="image" src="{{ form.instance.photoFile.url }}" rel="{{ form.instance.order }}">
							</div>
							<div class="settings">
								<div class="settings-header background-type-{{form.instance.photoType}}">
									<p>Inställningar</p>
								</div>
								<div class="settings-content">
									<p>Ta bort bilden permanent: </p> <a class="btn btn-primary delete" href="{% url 'dbtapp:photoRemoveEdit' video.pk form.instance.pk %}"><span class="glyphicon glyphicon-trash" id="hover-white" aria-hidden="true"></span></a> 
									<div>
										<button class="btn btn-primary settings-cancel">Avbryt</button>

                               			<input type="submit" value="Spara" class="btn btn-primary">
									</div>
								</div>
							</div>
							<div class="image-text-content"> 
								<div>
									<p>Ange bildtext:</p>
									{% render_field form.description class+="form-control" tabindex=1 %}
								</div>

							</div>
							<div class="close-btn-settings" href="#" title="Close"><span class="glyphicon glyphicon-remove" id="hover-white" aria-hidden="true"></span></div>
						</form>
						<!-- close settings -->

					</li>
					{% endfor %}
					{% endif %}
				</ul>

			</div>
		</div>


<script>
//var companyName = {{video.name}};
var postURL = "{% url 'dbtapp:videoEdit' video.pk %}";
var postLogoURL = "{% url 'dbtapp:logoPost' video.pk %}"
</script>


{% endblock %}

{% block leftNav %}
<a href="{% url 'dbtapp:videoStep' video.pk 3%}"><span id="navigationArrow" tabindex=4 class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
{% endblock %}

{% block rightNav %}
<a href="{% url 'dbtapp:phantomjspk' video.pk %}"><span id="navigationArrow" tabindex=3 class="glyphicon glyphicon-floppy-saved" aria-hidden="true"></span></a>
{% endblock %}

dbtapp/templates/dbtapp/stepBase.html
{% extends "dbtapp/base.html" %}
{% load staticfiles %}

{% block content %}
<script>
    var postURL = "{% url 'dbtapp:videoEdit' video.pk %}"
</script>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 text-left">
        <a id="preview-button" href="#preview" class="btn btn-primary">Förhandsvisa</a>
    </div>
</div>
<div class="spacing">   
</div>


<!-- Bildserie -->
<div class="row">
    <div class="col-md-12">
        <ul id="images" class="list-group">
            {% if settings %}
            {% for form in settings %}
            <li rel="{{ form.instance.pk }}" class="col-xs-1 list-type-{{form.instance.photoType}}">
                <form class="post-settings-form" action="{% url 'dbtapp:photoDescriptionPost' video.pk form.instance.pk%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% load widget_tweaks %}
                    <div class="image-wrapper">
                        <img class="image" src="{{ form.instance.photoFile.url }}" rel="{{ form.instance.order }}">
                    </div>
                    <div class="settings">
                        <div class="settings-header background-type-{{form.instance.photoType}}">
                            <p>Inställningar</p>
                        </div>
                        <div class="settings-content">
                            <p>
                                Välj animering.
                            
                                {% render_field form.animation class+="form-control" tabindex=1 %}
                            
                            
                                Ta bort bilden permanent.
                                <a class="btn btn-primary delete" href="{% url 'dbtapp:photoRemove' video.pk imgtype form.instance.pk %}">
                                    <span class="glyphicon glyphicon-trash" id="hover-white" aria-hidden="true"></span>
                                </a>
                            </p>
                            <div>
                                <button class="btn btn-primary settings-cancel">Avbryt</button>

                                <input type="submit" value="Spara" class="btn btn-primary">
                            </div>
                        </div>
                    </div>
                    <div class="image-text-content"> 
                        <div>
                            <p>Ange bildtext:</p>
                            {% render_field form.description class+="form-control" tabindex=1 %}
                        </div>
                        
                    </div>
                    <a class="close-btn-settings" href="#" title="Close"><span class="glyphicon glyphicon-remove" id="hover-white" aria-hidden="true"></span></a>
                </form>
                <!-- close settings -->
                
            </li>
            {% endfor %}
            {% endif %}

            <!-- Ladda upp bild -->
            <div id="addFileWrapper" >
                <span class="glyphicon glyphicon-plus"></span>
                <form action="{% url 'dbtapp:videoStep' video.pk imgtype %}" class="form-class clearfix" method="post" enctype="multipart/form-data">       
                    {% csrf_token %}
                    {{ form.photoFile }}
                </form>
            </div>
        </ul>

    </div>
</div>

<div id="preview" class="modalDialog">
            
    <div id="slideshow-container-steps">

        <!-- ändra här för kryss i preview på alla steg -->
        <a id="closeButton" href="#" title="Close"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
        {% include 'dbtapp/_videoPartial.html' %}
        <div id="controls">
            <div id="sliderWrapper">
                <div id="slider"></div>
                <button id="pause" type="button" class="btn btn-primary controll-button"><span class="glyphicon glyphicon-play"></span></button>
                <button id="repeat" type="button" class="btn btn-primary  controll-button"><span class="glyphicon glyphicon-repeat"></span></button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block navigation %}
<div class="spacing"></div>
<div class="row">

    <div class="col-xs-6 col-sm-6 col-md-1 text-left">
        <!-- Härifrån ska man kunna ta sig bakåt i stegen. -->
        {% block leftNav %}{% endblock %}
    </div>

    <div class="col-md-10 text-center" id="timeline">
      
        <!-- Tidslinje -->
        <div id="hlineLeft" class="hline"></div>
        <div id="hlineRight" class="hline"></div>

        <div class="round-button">
            <div class="round-button-circle" id="round-button-circle1">
                <a href="{% url 'dbtapp:videoUpdate'%}" class="round-button">1</a>
            </div>
        </div>

        <div class="round-button">
            <div class="round-button-circle" id="round-button-circle2">
                <a href="#" class="round-button">2</a>
            </div>
        </div>

        <div class="round-button">
            <div class="round-button-circle" id="round-button-circle3">
                <a href="#" class="round-button">3</a>
            </div>
        </div>
        
        <div class="round-button">
            <div class="round-button-circle" id="round-button-circle4">
                <a href="#" class="round-button">4</a>
            </div>
        </div>
        
        <div class="round-button">
            <div class="round-button-circle" id="round-button-circle5">
                <a href="#" class="round-button">5</a>
            </div>
        </div>

    </div>

    <div class="col-xs-6 col-sm-6 col-md-1 text-right">
        {% block rightNav %}
        {% endblock %}
        
        <!--<input type="submit" value="Nästa" />-->
    </div>
</div>
{% endblock %}

dbtapp/templates/dbtapp/upload.html
{% extends "dbtapp/base.html" %}
{% load staticfiles %}
	
{% block head %}
	LAVG
{% endblock %}

{% block content %}
	<form action="{% url upload_pic %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <p>
            <input id="id_image" type="file" class="" name="image">
        </p>
        <input type="submit" value="Submit" />
    </form>
	
	
{% endblock %}

dbtapp/templates/dbtapp/videoList.html
{% extends "dbtapp/base.html" %}
{% load staticfiles %}

<!--
{% block head %}
<div class="content" id="header">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-2 text-left">
            <h1>Bibliotek</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 text-left">
            <h2 id="description"> Här kan du se alla dina tidigare filmer. Klicka på en film för att fortsätta redigera.</h2> 
        </div>

    </div>
    <div class="spacing"></div>
</div>
{% endblock %}
-->

{% block headerNumber %}
Videobibliotek
{% endblock %}

{% block content %}

<script>
	setTimeout(function(){
		location.reload(true)
	}, 1000 * 30);
</script>

{% if video_list %}  
<div class="list-group clearfix"> 
    {% for video in video_list %}
    <div class="row spacing-list-group-item">
        <div class="col-xs-12 col-sm-12 col-md-7 col-md-offset-2 text-left">
            <a class="list-group-item" href="{% url 'dbtapp:videoUpdate' video.pk %}">{{ video.video_name }} - {{ video.company_name }} </a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'dbtapp:videoRemove' video.pk %}" class="btn btn-primary delete"><span class="glyphicon glyphicon-trash" id="hover-white" aria-hidden="true"></span></a>
			{% if video.video_url %}
			<a href={{ video.video_url }} class="btn btn-primary download"><span class="glyphicon glyphicon-save" id="hover-white" aria-hidden="true"></span></a>
			{% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
<div class="row spacing-list-group-item">
        <div class="col-xs-12 col-sm-12 col-md-7 col-md-offset-2 text-left">
            <h3>No videos are available.</h3>
    </div>
</div>

{% endif %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-5 col-md-offset-2 text-left">
        <div class="spacing"></div>
        <a href="{% url 'dbtapp:videoUpdate' %}" class="btn btn-primary">Skapa ny film!</a>
    </div>
</div>
{% endblock %}